[tool.ruff]
line-length = 88
select = ["E", "F", "I", "UP", "N", "S", "C", "B"]
ignore = ["B008"]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]

[tool.pytest.ini_options]
pythonpath = "alchemist"
testpaths = "tests"
asyncio_mode = "auto"

[tool.pyright]
venvPath = "."
venv = "venv"
